name: sam_adapt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0.1
  - numpy=1.24.3
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn
  - scipy
  - scikit-learn
  - jupyter
  - notebook
  - ipykernel
  - ipywidgets
  - tqdm
  - monai=1.1.0
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - matplotlib-inline
  - imageio
  - imagecodecs
  - pillow
  - aiohttp
  - async-timeout
  - attrs
  - cffi
  - cryptography
  - cytoolz
  - cloudpickle
  - fsspec
  - joblib
  - kiwisolver
  - packaging
  - protobuf
  - pip:
      - opencv-python
      - nibabel
